name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create .env variable
      run: |
        touch .env
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
        echo "PORT=80" >> .env
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend:$(date +%s)
